// Package problem implements RFC 7807 / RFC 9457 "Problem Details for HTTP
// APIs" for the aarv framework.
//
// A Problem Details object is a JSON document with five standard members
// (type, title, status, detail, instance) plus arbitrary extension members.
// It is served with the media type "application/problem+json" so that
// generic HTTP clients can recognize the response as a structured error
// rather than a free-form payload.
//
// # Wiring
//
// Install the handler via [aarv.WithErrorHandler]:
//
//	app := aarv.New(
//	    aarv.WithErrorHandler(problem.Handler(problem.Config{
//	        Type: "https://api.example.com/problems",
//	        TypeForCode: map[string]string{
//	            "validation_failed":  "https://api.example.com/problems/validation",
//	            "unauthorized":       "https://api.example.com/problems/unauthorized",
//	        },
//	        Instance: func(c *aarv.Context) string { return c.Path() },
//	    })),
//	)
//
// Per-route opt-in/out is achieved by installing or omitting the handler
// at construction time. Route-level toggling would require invasive
// changes to the framework's error pipeline and is intentionally out of
// scope for this plugin; callers needing it can wrap the handler
// themselves and switch on a route-scoped store value.
//
// # Extension members
//
// Extensions are flattened into the top-level JSON object per RFC 7807
// §3.2. Reserved standard-member keys ("type" / "title" / "status" /
// "detail" / "instance") are stripped from the Extensions copy so an
// extension can never inject a forged standard member, even when the
// corresponding struct field is the zero value. The handler
// automatically adds a "request_id" extension when the framework's
// request-id middleware has run.
package problem

import (
	"encoding/json"
	"errors"
	"net/http"

	"github.com/nilshah80/aarv"
)

// DefaultType is the RFC 7807 §4.2 default ("about:blank") indicating
// the problem has no semantics beyond the HTTP status code.
const DefaultType = "about:blank"

// ContentType is the RFC 7807 §3 media type for problem documents.
const ContentType = "application/problem+json"

// Details is an RFC 7807 / RFC 9457 Problem Details object.
//
// All five standard members are optional per the spec; Type defaults to
// DefaultType when empty. Extensions are flattened into the top-level
// JSON object on marshal; reserved standard-member keys ("type" /
// "title" / "status" / "detail" / "instance") are stripped from the
// Extensions copy so an extension cannot impersonate a standard field
// regardless of which struct fields are populated.
type Details struct {
	// Type is a URI reference identifying the problem type. Empty
	// values marshal as "about:blank".
	Type string

	// Title is a short, human-readable summary of the problem type.
	// Should not change between occurrences of the same type.
	Title string

	// Status is the HTTP status code generated by the origin server for
	// this occurrence. Zero is omitted from the output.
	Status int

	// Detail is a human-readable explanation specific to this occurrence.
	Detail string

	// Instance is a URI reference identifying this specific occurrence.
	Instance string

	// Extensions are arbitrary additional members merged into the top-
	// level JSON object on marshal. Use lowercase, RFC 8259-valid keys
	// to avoid surprises in clients with strict schemas.
	Extensions map[string]any
}

// MarshalJSON serializes the Details into a JSON object with extensions
// flattened to the top level (RFC 7807 §3.2). Reserved standard-member
// keys ("type" / "title" / "status" / "detail" / "instance") are
// stripped from Extensions during the copy so an extension can never
// inject a forged standard member — even when the corresponding
// standard field on the struct is the zero value (in which case the
// non-overwrite path below would otherwise leave the extension's value
// in place).
//
// The "type" member is always present (defaulting to DefaultType when
// Type is empty); other standard members are emitted only when non-zero
// to match common JSON conventions and keep the wire shape minimal.
//
// Receiver is by value so json.Marshal(Details{...}) (value) and
// json.Marshal(&Details{...}) (pointer) both flow through this method —
// otherwise the value form would silently bypass the custom marshaler
// and emit Go field names plus a nested "Extensions" object.
func (d Details) MarshalJSON() ([]byte, error) {
	out := make(map[string]any, 5+len(d.Extensions))

	// Copy extensions first, skipping any key that would collide with a
	// standard member. Without this skip, an Extensions entry could
	// impersonate a standard field whenever the corresponding struct
	// field is the zero value (RFC 7807 §3.2: extension members must
	// not duplicate standard names).
	for k, v := range d.Extensions {
		if isReservedKey(k) {
			continue
		}
		out[k] = v
	}

	typ := d.Type
	if typ == "" {
		typ = DefaultType
	}
	out["type"] = typ
	if d.Title != "" {
		out["title"] = d.Title
	}
	if d.Status != 0 {
		out["status"] = d.Status
	}
	if d.Detail != "" {
		out["detail"] = d.Detail
	}
	if d.Instance != "" {
		out["instance"] = d.Instance
	}

	return json.Marshal(out)
}

// isReservedKey reports whether k is the name of an RFC 7807 standard
// member. Used by MarshalJSON to strip would-be impersonators from
// Extensions before flatten.
func isReservedKey(k string) bool {
	switch k {
	case "type", "title", "status", "detail", "instance":
		return true
	}
	return false
}

// Config controls how Handler converts errors into Problem Details.
type Config struct {
	// Type is the default "type" URI applied to every problem when
	// TypeForCode does not override it. Empty falls back to DefaultType
	// ("about:blank"). Recommend a stable, dereferenceable URL that
	// documents the application's error class taxonomy.
	Type string

	// TypeForCode maps an *aarv.AppError.Code() value to a "type" URI.
	// Lets users serve resolution docs from a stable URL per error
	// class. When the error is not an *AppError, or its Code is not in
	// the map, Config.Type (or DefaultType) is used.
	TypeForCode map[string]string

	// Instance, when non-nil, is invoked per error to produce the
	// per-occurrence "instance" URI. A common shape is
	// func(c) string { return c.Path() }. Returning "" omits the
	// member from the response.
	Instance func(c *aarv.Context) string

	// OnInternal lets callers log or instrument 5xx responses where
	// the original failure carries diagnostic value the wire response
	// deliberately hides. It fires in two cases:
	//
	//   - the error is neither *AppError nor *ValidationErrors and
	//     therefore degrades to a generic 500 (callback receives the
	//     raw err);
	//   - the error IS an *aarv.AppError with a non-nil Internal()
	//     (the aarv.ErrInternal(downstream) shape) and the resolved
	//     status is >= 500 (callback receives the unwrapped Internal()
	//     err — matching the framework default ErrorHandler's
	//     "internal error" slog line).
	//
	// It does NOT fire for plain *AppError 5xx with no Internal()
	// (e.g. ErrServiceUnavailable("draining"), ErrGatewayTimeout(...))
	// — the caller chose that status to communicate state to the
	// client, not to signal a fault. nil disables the hook entirely.
	OnInternal func(c *aarv.Context, err error)
}

// Handler returns an [aarv.ErrorHandler] that serializes any error from
// the chain as application/problem+json per RFC 7807. Wire it into the
// framework via [aarv.WithErrorHandler].
//
// Conversion rules:
//   - *aarv.AppError → status, code, message, detail mapped onto
//     Status, Title, Detail (Title falls back to http.StatusText when
//     Code is empty); Type resolved via Config.TypeForCode then Config.Type.
//   - *aarv.ValidationErrors → 422, Title "Validation failed", with the
//     per-field details exposed under the "errors" extension.
//   - Anything else → 500, code "internal_error", original message
//     hidden from the wire (the standard "Internal server error" text
//     is used). The OnInternal callback receives the unmasked error
//     for logging.
//
// The framework's request-id, when present on the *Context, is added
// as the "request_id" extension so problems can be correlated with
// server-side logs.
func Handler(cfg Config) aarv.ErrorHandler {
	return func(c *aarv.Context, err error) {
		details := buildDetails(cfg, c, err)
		_ = c.Blob(details.Status, ContentType, marshalOrFallback(details))
	}
}

// marshalOrFallback serializes d, returning the static fallbackBody
// when json.Marshal fails. Marshal can only fail when an extension
// carries a non-marshalable value (channel, func, complex) — none of
// the FromError / ValidationProblem paths produce those, so this is a
// defense-in-depth path for callers that hand-construct or mutate
// Details before passing it through the handler. Extracted so tests
// can drive both arms deterministically.
func marshalOrFallback(d *Details) []byte {
	body, err := json.Marshal(d)
	if err != nil {
		return fallbackBody(d.Status)
	}
	return body
}

// buildDetails turns an error into a *Details using cfg's mappings and
// c's request_id. Exposed via FromError when callers want the result
// without the wire-write side effect.
func buildDetails(cfg Config, c *aarv.Context, err error) *Details {
	d := FromError(err)

	// Type resolution: Code-specific override → Config.Type → leave
	// empty (MarshalJSON will substitute DefaultType).
	if d.Type == "" {
		var appErr *aarv.AppError
		if errors.As(err, &appErr) {
			if t, ok := cfg.TypeForCode[appErr.Code()]; ok {
				d.Type = t
			}
		}
		if d.Type == "" && cfg.Type != "" {
			d.Type = cfg.Type
		}
	}

	if cfg.Instance != nil && d.Instance == "" {
		d.Instance = cfg.Instance(c)
	}

	// request_id extension — only when the requestid plugin (or any
	// other middleware) has populated it.
	if rid := c.RequestID(); rid != "" {
		if d.Extensions == nil {
			d.Extensions = make(map[string]any, 1)
		}
		d.Extensions["request_id"] = rid
	}

	if cfg.OnInternal != nil && d.Status >= http.StatusInternalServerError {
		// Three cases for 5xx responses:
		//   1. err is not an *AppError → caller didn't classify this
		//      explicitly; surface the raw err for logging.
		//   2. err is an *AppError with a non-nil Internal() (the
		//      ErrInternal(internal) shape) → caller wrapped a
		//      downstream failure. The internal err is what's
		//      diagnostically useful; surface it. The framework's own
		//      default handler logs in this same case (server.go
		//      handleError → "internal error" slog line) so this
		//      keeps observability parity for users who switch to
		//      problem+json.
		//   3. err is an *AppError with no Internal() → caller
		//      explicitly chose 503/504 to communicate a state to the
		//      client (e.g. ErrServiceUnavailable("draining")). Don't
		//      fire OnInternal — that would generate noise on routine
		//      backpressure / maintenance signals.
		var appErr *aarv.AppError
		switch {
		case !errors.As(err, &appErr):
			cfg.OnInternal(c, err)
		case appErr.Internal() != nil:
			cfg.OnInternal(c, appErr.Internal())
		}
	}

	return d
}

// FromError converts a chain error into a Details object using the same
// classification rules as Handler. Useful for callers that need the
// structured form before serialization (e.g. for audit logging or
// composing a higher-level response). Type is left empty here — the
// caller (or Handler) decides resolution.
func FromError(err error) *Details {
	if err == nil {
		return &Details{
			Status: http.StatusOK,
			Title:  http.StatusText(http.StatusOK),
		}
	}

	var validationErrs *aarv.ValidationErrors
	if errors.As(err, &validationErrs) {
		return ValidationProblem(validationErrs)
	}

	var appErr *aarv.AppError
	if errors.As(err, &appErr) {
		title := appErr.Code()
		if title == "" {
			title = http.StatusText(appErr.StatusCode())
		}
		return &Details{
			Status: appErr.StatusCode(),
			Title:  title,
			Detail: combineMessageAndDetail(appErr.Message(), appErr.Detail()),
		}
	}

	// Generic / unknown — never leak the underlying message to the
	// client (it may include database errors, stack traces, etc.).
	return &Details{
		Status: http.StatusInternalServerError,
		Title:  "internal_error",
		Detail: http.StatusText(http.StatusInternalServerError),
	}
}

// ValidationProblem wraps an [aarv.ValidationErrors] into a Details with
// status 422, title "Validation failed", and the per-field failures
// exposed under the "errors" extension. The extension value is the
// underlying []ValidationError slice — clients consuming the response
// can decode it directly into the same shape used by the framework's
// non-RFC-7807 error path.
//
// Returns a *Details with Type left empty; callers (or Handler's Type/
// TypeForCode resolution) supply the URI.
func ValidationProblem(errs *aarv.ValidationErrors) *Details {
	if errs == nil {
		return &Details{
			Status: http.StatusUnprocessableEntity,
			Title:  "Validation failed",
		}
	}
	return &Details{
		Status: http.StatusUnprocessableEntity,
		Title:  "Validation failed",
		Detail: errs.Error(),
		Extensions: map[string]any{
			"errors": errs.Errors,
		},
	}
}

// combineMessageAndDetail folds AppError.Message() and AppError.Detail()
// into a single "detail" string. RFC 7807 has no equivalent of the
// framework's separate "detail" field, so we merge — with the message
// as the primary text and the detail appended in parentheses when
// present. Either being empty falls back to the other.
func combineMessageAndDetail(msg, detail string) string {
	switch {
	case msg == "" && detail == "":
		return ""
	case detail == "":
		return msg
	case msg == "":
		return detail
	default:
		return msg + " (" + detail + ")"
	}
}

// fallbackBody is the static document Handler emits when json.Marshal
// of the Details map fails (only possible if an extension carries an
// unmarshalable value). Hardcoded so it cannot itself fail to marshal.
func fallbackBody(status int) []byte {
	if status == 0 {
		status = http.StatusInternalServerError
	}
	// Minimal RFC 7807-conformant document.
	return []byte(`{"type":"` + DefaultType + `","title":"internal_error","status":` +
		itoa(status) + `,"detail":"problem details serialization failed"}`)
}

// itoa is a tiny zero-alloc int-to-string for HTTP status codes (0–599)
// used in fallbackBody. Keeps fallbackBody dep-free of strconv just to
// underscore that it is a pure last-resort path.
func itoa(n int) string {
	if n < 0 || n > 999 {
		return "500"
	}
	if n < 10 {
		return string([]byte{'0' + byte(n)})
	}
	if n < 100 {
		return string([]byte{'0' + byte(n/10), '0' + byte(n%10)})
	}
	return string([]byte{'0' + byte(n/100), '0' + byte((n/10)%10), '0' + byte(n%10)})
}
